import {appSchema, tableSchema} from '@nozbe/watermelondb';

export default appSchema({
  version: 1,
  tables: [
    tableSchema({
      name: 'deliverylists',
      columns: [
        {name: 'id_db', type: 'number'},
        {name: 'event_id_db', type: 'number'},
        {name: 'event_name', type: 'string'},
        {name: 'name', type: 'string'},
        {name: 'beneficiary_initials', type: 'string'},
      ],
    }),
    tableSchema({
      name: 'deliveries',
      columns: [
        {name: 'id_db', type: 'number'},
        {name: 'address_latitude', type: 'number'},
        {name: 'address_longitude', type: 'number'},
        {name: 'amount', type: 'number'},
        {name: 'beneficiary_age', type: 'number'},
        {name: 'beneficiary_id_db', type: 'number'},
        {name: 'city_id_db', type: 'number'},
        {name: 'city_latitude', type: 'number'},
        {name: 'city_longitude', type: 'number'},
        {name: 'delivered_by_id_db', type: 'number'},
        {name: 'delivery_event_id_db', type: 'number'},
        {name: 'delivery_list_id_db', type: 'number'},
        {name: 'delivered_date', type: 'string'},
        {name: 'enrollment_id_db', type: 'number'},
        {name: 'locality_id_db', type: 'number'},
        {name: 'locality_latitude', type: 'number'},
        {name: 'locality_longitude', type: 'number'},
        {name: 'school_id_db', type: 'number'},
        {name: 'school_latitude', type: 'number'},
        {name: 'school_longitude', type: 'number'},
        {name: 'program_social_id_db', type: 'number'},
        {name: 'social_program_announcement_id_db', type: 'number'},
        {name: 'beneficiary_birthday', type: 'string'},
        {name: 'beneficiary_curp', type: 'string'},
        {name: 'beneficiary_email', type: 'string'},
        {name: 'beneficiary_gender', type: 'string'},
        {name: 'beneficiary_lastname', type: 'string'},
        {name: 'beneficiary_name', type: 'string'},
        {name: 'card_number', type: 'string'},
        {name: 'city_name', type: 'string'},
        {name: 'comments', type: 'string'},
        {name: 'face_encodings', type: 'string'},
        {name: 'full_address', type: 'string'},
        {name: 'locality_name', type: 'string'},
        {name: 'school_level', type: 'string'},
        {name: 'school_name', type: 'string'},
        {name: 'status', type: 'string'},
        {name: 'photo', type: 'string'},
        {name: 'profile_photo', type: 'string'},
        {name: 'receipt_photo', type: 'string'},
        {name: 'is_synced', type: 'boolean'},
      ],
    }),
    tableSchema({
      name: 'photos',
      columns: [
        {name: 'user_id_db', type: 'number'},
        {name: 'delivery_id_db', type: 'number'},
        {name: 'field_to_fill', type: 'string'},
        {name: 'photo', type: 'string'},
        {name: 'is_synced', type: 'boolean'},
      ],
    }),
  ],
});
